[package]
name = "pacs-web"
description = "axum:QIDO/WADO/STOW-RS 与认证 API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
pacs-core.workspace = true
pacs-db.workspace = true
pacs-auth.workspace = true
pacs-store.workspace = true
pacs-codec.workspace = true
pacs-dimse.workspace = true
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
dicom.workspace = true
dicom-json.workspace = true
sqlx.workspace = true
uuid.workspace = true
chrono.workspace = true
sha2.workspace = true
mime.workspace = true
multer.workspace = true
reqwest.workspace = true
compress-tools.workspace = true
zip.workspace = true
libc.workspace = true
tempfile.workspace = true

[dev-dependencies]
pacs-core = { workspace = true, features = ["fixtures"] }
dotenvy.workspace = true
tower.workspace = true
