import {
  ChevronLeft,
  ChevronRight,
  Crosshair,
  Circle,
  Contrast,
  DraftingCompass,
  Eye,
  Eraser,
  FlipHorizontal2,
  FlipVertical2,
  FolderOpen,
  History,
  Info,
  Check,
  Edit3,
  Layers3,
  LogIn,
  LogOut,
  ListChecks,
  Move,
  MousePointer2,
  PanelRightClose,
  RotateCcw,
  RotateCw,
  Redo2,
  RefreshCw,
  Ruler,
  Search,
  ScanSearch,
  ScanLine,
  SlidersHorizontal,
  Square,
  Trash2,
  Undo2,
  Users,
  X,
  createIcons,
} from 'lucide';
import { App } from './app';
import './styles.css';

window.addEventListener('DOMContentLoaded', () => {
  createIcons({
    icons: {
      ChevronLeft,
      ChevronRight,
      Crosshair,
      Circle,
      Contrast,
      DraftingCompass,
      Eye,
      Eraser,
      FlipHorizontal2,
      FlipVertical2,
      FolderOpen,
      History,
      Info,
      Check,
      Edit3,
      Layers3,
      LogIn,
      LogOut,
      ListChecks,
      Move,
      MousePointer2,
      PanelRightClose,
      RotateCcw,
      RotateCw,
      Redo2,
      RefreshCw,
      Ruler,
      Search,
      ScanSearch,
      ScanLine,
      SlidersHorizontal,
      Square,
      Trash2,
      Undo2,
      Users,
      X,
    },
  });
  new App();
});
