import {
  ArchiveRestore,
  ArrowLeft,
  Blend,
  Bold,
  BookmarkPlus,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Crosshair,
  Circle,
  Contrast,
  DraftingCompass,
  Ellipsis,
  Eye,
  Eraser,
  FlipHorizontal2,
  FlipVertical2,
  FileArchive,
  FileText,
  FolderOpen,
  FolderUp,
  History,
  Image,
  Info,
  Italic,
  Check,
  Edit3,
  Layers3,
  LayoutGrid,
  Link,
  List,
  ListOrdered,
  LogIn,
  LogOut,
  ListChecks,
  Move,
  MousePointer2,
  Network,
  PanelRightClose,
  Paintbrush,
  Pencil,
  Pause,
  Play,
  RotateCcw,
  RotateCw,
  Redo2,
  RefreshCw,
  Ruler,
  Search,
  ScanSearch,
  ScanLine,
  Save,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Square,
  Sparkles,
  Sun,
  Trash2,
  Underline,
  Undo2,
  Upload,
  Users,
  X,
  createIcons,
} from 'lucide';
import { App } from './app';
import './styles.css';

window.addEventListener('DOMContentLoaded', () => {
  createIcons({
    icons: {
      ArchiveRestore,
      ArrowLeft,
      Blend,
      Bold,
      BookmarkPlus,
      ChevronDown,
      ChevronLeft,
      ChevronRight,
      Crosshair,
      Circle,
      Contrast,
      DraftingCompass,
      Ellipsis,
      Eye,
      Eraser,
      FlipHorizontal2,
      FlipVertical2,
      FileArchive,
      FileText,
      FolderOpen,
      FolderUp,
      History,
      Image,
      Info,
      Italic,
      Check,
      Edit3,
      Layers3,
      LayoutGrid,
      Link,
      List,
      ListOrdered,
      LogIn,
      LogOut,
      ListChecks,
      Move,
      MousePointer2,
      Network,
      PanelRightClose,
      Paintbrush,
      Pencil,
      Pause,
      Play,
      RotateCcw,
      RotateCw,
      Redo2,
      RefreshCw,
      Ruler,
      Search,
      ScanSearch,
      ScanLine,
      Save,
      Share2,
      ShieldCheck,
      SlidersHorizontal,
      Square,
      Sparkles,
      Sun,
      Trash2,
      Underline,
      Undo2,
      Upload,
      Users,
      X,
    },
  });

  if (new URLSearchParams(window.location.search).get('mode') === 'report') {
    // 报告独立小窗：隐藏登录屏与主阅片器，只初始化报告 UI
    const login = document.getElementById('login-screen');
    const shell = document.getElementById('app-shell');
    if (login) login.hidden = true;
    if (shell) shell.style.display = 'none';
    const root = document.getElementById('report-window-root');
    if (root) root.hidden = false;
    void import('./report-window').then(({ ReportWindow }) => new ReportWindow().init());
    return;
  }
  new App();
});
